### ISSUE TITLE
Could not parse launch file. Error at line 1.

### ISSUE THREAD

**Issue by varunchandak** [harrysethi/Tambola-Ticket-Generator#1]
java version "1.8.0_251"
Windows 10

![image](https://user-images.githubusercontent.com/18713091/80315622-70b83580-8816-11ea-9ce9-05422a731348.png)

**Comment by harrysethi** [comment]
were you able to make it work? the error seems weird.

**Comment by varunchandak** [comment]
Can you show me if you can run this on windows 10 box ?

**Comment by harrysethi** [comment]
sure, let me try it tomorrow.
I think you may be right, I did write it on ubuntu. I use Windows10 now, let me check and get back.

thanks for reporting the issue :)

**Comment by harrysethi** [comment]
just ran it on my windows10 JavaSE13 & it works like a charm

**Comment by varunchandak** [comment]
can you share the command and screenshot of it ?

**Comment by harrysethi** [comment]
![image](https://user-images.githubusercontent.com/8398579/80870969-7eaf0000-8cc7-11ea-9888-d6660b1a7d40.png)
Simply copied the code to a new java project.
