### ISSUE TITLE
Licensing Agreement

### ISSUE THREAD

**Issue by psibal** [harrysethi/Tambola-Ticket-Generator#2]
Hello Harinder,
This is Pavan. Really appreciate the code you have developed to create Tambola tickets.
I would like to use the code from the repo for my application. Am I okay to use the code in my application. I do not see any Licensing information for the same.

Thanks
Pavan

**Comment by harrysethi** [comment]
added, thanks for checking Pavan :)

https://github.com/harrysethi/Tambola-Ticket-Generator/blob/master/license

**Comment by psibal** [comment]
Sure Harinder. Will do. Thanks
