### ISSUE TITLE
Check this out..

### ISSUE THREAD

**Issue by TummanapallyAnuraag** [harrysethi/Tambola-Ticket-Generator#3]
Following your README.md file, 
I have created this [Tambola](https://tummanapallyanuraag.github.io/games/housie/), you can see my source code [here](https://github.com/TummanapallyAnuraag/games).

Thank you @harrysethi

**Comment by harrysethi** [comment]
awesome, it looks great.
just a couple of things, in case you want to add features in the next version:
1. It makes it more fun if people get to cut the numbers
2. Multiple category awards - First 5, rows, 4 corners, etc.
3. Tiebreakers (calling 'dibs') with a button - who gets to win if two players cut the first row at the same time. Maybe some buttons (one for each category) & whoever clicks (claims) first wins.

Thanks for mentioning :)
